---
abstract: 'A test distribution for Github'
author:
  - 'Mark Allen <mrallen1@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Github-Test
provides:
  Acme::Github::Test:
    file: lib/Acme/Github/Test.pm
    version: 0.01
requires:
  perl: 5.014
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/mrallen1/Acme-Github-Test.git
version: 0.01
